import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const interFont = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={`${interFont.className} h-full antialiased`}>
      <body className="flex min-h-full flex-col bg-navy-950 text-navy-50">{children}</body>
    </html>
  )
}
